/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PriceData {
  'eurGbp' : number,
  'eurJpy' : number,
  'eurUsd' : number,
  'usdCad' : number,
  'usdJpy' : number,
  'audUsd' : number,
  'nzdUsd' : number,
  'gbpUsd' : number,
}
export type Result = { 'ok' : PriceData } |
  { 'err' : string };
export type Result_1 = { 'ok' : [] | [PriceData] } |
  { 'err' : string };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  /**
   * / Returns the last time prices were fetched
   */
  'getLastFetchTime' : ActorMethod<[], bigint>,
  /**
   * / Returns last cached prices if available
   */
  'getLastPrices' : ActorMethod<[], Result_1>,
  'getLivePrices' : ActorMethod<[], Result>,
  /**
   * / Transform callback for filtering HTTP response headers.
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];