/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceData = IDL.Record({
  'eurGbp' : IDL.Float64,
  'eurJpy' : IDL.Float64,
  'eurUsd' : IDL.Float64,
  'usdCad' : IDL.Float64,
  'usdJpy' : IDL.Float64,
  'audUsd' : IDL.Float64,
  'nzdUsd' : IDL.Float64,
  'gbpUsd' : IDL.Float64,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Opt(PriceData),
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : PriceData, 'err' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getLastFetchTime' : IDL.Func([], [IDL.Int], ['query']),
  'getLastPrices' : IDL.Func([], [Result_1], ['query']),
  'getLivePrices' : IDL.Func([], [Result], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceData = IDL.Record({
    'eurGbp' : IDL.Float64,
    'eurJpy' : IDL.Float64,
    'eurUsd' : IDL.Float64,
    'usdCad' : IDL.Float64,
    'usdJpy' : IDL.Float64,
    'audUsd' : IDL.Float64,
    'nzdUsd' : IDL.Float64,
    'gbpUsd' : IDL.Float64,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Opt(PriceData), 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : PriceData, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getLastFetchTime' : IDL.Func([], [IDL.Int], ['query']),
    'getLastPrices' : IDL.Func([], [Result_1], ['query']),
    'getLivePrices' : IDL.Func([], [Result], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };